services:
  backend:
    build: 
      context: ./BackCesiZen
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./BackCesiZen/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./BackCesiZen/uploads:/app/uploads
      - ./BackCesiZen:/app/data

  frontend:
    build:
      context: ./FrontCesiZen
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

